CREATE PROCEDURE CreateGames
AS
	CREATE TABLE Games
	(
		Id INT NOT NULL IDENTITY (1,1),
		Name NVARCHAR(75) NOT NULL,
		Genre NVARCHAR(50) NOT NULL,
		Description NVARCHAR(MAX) NULL,
		CreatedAt DATE DEFAULT GETDATE() NOT NULL,
		GameListId INT NOT NULL
		CONSTRAINT PK_Games PRIMARY KEY CLUSTERED (Id ASC)
		CONSTRAINT FK_Games_GameLists FOREIGN KEY (GameListId) REFERENCES GameLists (Id)
	)